server:
  port: 8082

## gateway
spring:
  cloud.gateway.routes:
    - id: api-service-route
      uri: http://localhost:8080
      predicates:
        - Path=/api/**
      filters:
        - StripPrefix=1
    - id: auth-service-route
      uri: http://localhost:8081
      predicates:
        - Path=/auth/**
      filters:
        - StripPrefix=1
    - id: test-service-route
      uri: http://localhost:8088
      predicates:
        - Path=/test/**
      filters:
        - StripPrefix=1
  security.oauth2.resourceserver.jwt.jwk-set-uri: 'http://localhost:8081/.well-known/jwks.json'